# Build Docker image and push to Docker Hub (tag-driven)
name: build-and-push-docker-image

on:
  # Run only when a git tag like "v2.2.1" is pushed
  push:
    tags:
      - 'v*'
  # allow manual runs (will NOT push unless a tag ref is used)
  workflow_dispatch:

env:
  DOCKER_IMAGE: ohdsi/broadsea-atlasdb

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Extract Docker metadata (use git tag vX.Y.Z -> image tag X.Y.Z)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            # Also tag as "latest" on tagged releases
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push (only on tags)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_BRANCH=${{ steps.meta.outputs.version }}
            GIT_COMMIT_ID_ABBREV=${{ github.sha || '' }}

      - name: Log generated Docker image tags
        run: |
          echo "Generated tags:"
          echo "${{ steps.meta.outputs.tags }}"
